[package]
name = "lib412"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdnative = { version = "0.11" }
postgres = "0.19.4"
r2d2 = "0.8.10"
r2d2_postgres = "0.18.1"
